//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5_1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyProgram
    {
        public int CustomerId { get; set; }
        public int Points { get; set; }
        public string MembershipTier { get; set; }
    }
}
