//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5_1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.QuantityBasedRuleDetails = new HashSet<QuantityBasedRuleDetail>();
        }
    
        public int PromotionId { get; set; }
        public string PromotionName { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public string ApplicableProducts { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> MinimumOrderValue { get; set; }
        public int Priority { get; set; }
        public string QuantityBasedRules { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuantityBasedRuleDetail> QuantityBasedRuleDetails { get; set; }
    }
}
